[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "formseal-decrypt"
version = "0.2.0"
description = "CLI tool for decrypting formseal ciphertexts"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.8"
authors = [
    {name = "grayguava"}
]
dependencies = [
    "keyring>=25.0",
    "pynacl>=1.5.0",
]

[project.scripts]
fsd = "fsd.fsd:main"

[tool.setuptools]
packages = [
    "fsd",
    "fsd.ui",
    "fsd.commands",
    "fsd.commands.general",
    "fsd.commands.config",
    "fsd.commands.connect",
    "fsd.commands.decrypt",
    "fsd.security",
    "fsd.formats",
]